#!/usr/bin/env bash
set -euo pipefail

export PYTHONNOUSERSITE=1
export PYTHONDONTWRITEBYTECODE=1
: "${PROJECT_DIR:?PROJECT_DIR is required}"
source "${PROJECT_DIR}/sbatch/common.sh"
hlt_activate
export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
: "${HCWDL_REPRESENTATION_NONFINAL_ACCEPTANCE_AUTHORITY:?HCWDL_REPRESENTATION_NONFINAL_ACCEPTANCE_AUTHORITY is required}"
: "${HCWDL_REPRESENTATION_NONFINAL_ACCEPTANCE_ACTION:?HCWDL_REPRESENTATION_NONFINAL_ACCEPTANCE_ACTION is required}"

exec python -s "${PROJECT_DIR}/scripts/run_hcwdl_representation_nonfinal_acceptance_action.py" \
  --authority "${HCWDL_REPRESENTATION_NONFINAL_ACCEPTANCE_AUTHORITY}" \
  --action "${HCWDL_REPRESENTATION_NONFINAL_ACCEPTANCE_ACTION}"
