"""Versioned artifacts for HCWDL-MHPE-THREE-TRACK-60E-FULL."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Final, Mapping

from hlt_classification.data.cache_contracts import (
    require_sha256, validate_content_hash, with_content_hash,
)


GRAPH_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_GRAPH/v1"
NODE_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_NODE_SPEC/v1"
RECIPE_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_RECIPE/v1"
INTEGRATION_LOCK_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_INTEGRATION_LOCK/v1"
TEST_EVIDENCE_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_TEST_EVIDENCE/v1"
FOUNDATION_LOCK_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_FOUNDATION_LOCK/v1"
ENDPOINT_RESOURCE_LOCK_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_ENDPOINT_RESOURCE_LOCK/v1"
PROBABILITY_SHARD_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_PROBABILITY_SHARD/v1"
PROBABILITY_MANIFEST_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_PROBABILITY_MANIFEST/v1"
PROBABILITY_LOCK_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_PROBABILITY_LOCK/v1"
EPHEMERAL_REP_AUDIT_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_EPHEMERAL_REP_AUDIT/v1"
TRAINING_REPORT_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_TRAINING_REPORT/v1"
SELECTED_CHECKPOINT_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_SELECTED_CHECKPOINT/v1"
FINAL_CHECKPOINT_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_FINAL_CHECKPOINT/v1"
DEPLOYABLE_CHECKPOINT_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_DEPLOYABLE_CHECKPOINT/v1"
STAGE_REPORT_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_STAGE_REPORT/v1"
CAMPAIGN_SPEC_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_CAMPAIGN_SPEC/v1"
COMMAND_PLAN_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_COMMAND_PLAN/v1"
RUNTIME_PROFILE_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_RUNTIME_PROFILE/v1"
AGGREGATE_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_AGGREGATE/v1"
FINALIST_LOCK_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_FINALIST_LOCK/v1"
EXECUTION_LOCK_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_EXECUTION_LOCK/v1"
CAMPAIGN_COMPLETE_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_CAMPAIGN_COMPLETE/v1"
RECOVERY_SPEC_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_RECOVERY_SPEC/v1"
RESOURCE_RECOVERY_SPEC_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_RESOURCE_RECOVERY_SPEC/v1"
COMPOSITE_RECOVERY_SPEC_CONTRACT: Final = (
    "HCWDL_MHPE_THREE_TRACK_60E_COMPOSITE_RECOVERY_SPEC/v1"
)
MONITOR_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_MONITOR/v1"
CANCELLATION_CONTRACT: Final = "HCWDL_MHPE_THREE_TRACK_60E_CANCELLATION/v1"
INTERRUPTION_ATTESTATION_CONTRACT: Final = (
    "HCWDL_MHPE_THREE_TRACK_60E_INTERRUPTION_ATTESTATION/v1"
)
D000_CROSS_TRACK_ENSEMBLE_REPORT_CONTRACT: Final = (
    "HCWDL_MHPE_THREE_TRACK_60E_D000_CROSS_TRACK_ENSEMBLE_REPORT/v1"
)
D000_LOGIT_RSET_BLEND_REPORT_CONTRACT: Final = (
    "HCWDL_MHPE_THREE_TRACK_60E_D000_LOGIT_RSET_BLEND_REPORT/v1"
)
D000_LOGIT_RSET_FLAT8_REPORT_CONTRACT: Final = (
    "HCWDL_MHPE_THREE_TRACK_60E_D000_LOGIT_RSET_FLAT8_REPORT/v1"
)
SCHEMA_VERSION: Final = 1

CONTRACTS: Final = (
    GRAPH_CONTRACT, NODE_CONTRACT, RECIPE_CONTRACT, INTEGRATION_LOCK_CONTRACT,
    TEST_EVIDENCE_CONTRACT,
    FOUNDATION_LOCK_CONTRACT, ENDPOINT_RESOURCE_LOCK_CONTRACT,
    PROBABILITY_SHARD_CONTRACT, PROBABILITY_MANIFEST_CONTRACT,
    PROBABILITY_LOCK_CONTRACT, EPHEMERAL_REP_AUDIT_CONTRACT,
    TRAINING_REPORT_CONTRACT, SELECTED_CHECKPOINT_CONTRACT,
    FINAL_CHECKPOINT_CONTRACT, DEPLOYABLE_CHECKPOINT_CONTRACT,
    STAGE_REPORT_CONTRACT, CAMPAIGN_SPEC_CONTRACT,
    COMMAND_PLAN_CONTRACT, RUNTIME_PROFILE_CONTRACT, AGGREGATE_CONTRACT,
    FINALIST_LOCK_CONTRACT, EXECUTION_LOCK_CONTRACT,
    CAMPAIGN_COMPLETE_CONTRACT, RECOVERY_SPEC_CONTRACT,
    RESOURCE_RECOVERY_SPEC_CONTRACT, COMPOSITE_RECOVERY_SPEC_CONTRACT,
    MONITOR_CONTRACT,
    CANCELLATION_CONTRACT, INTERRUPTION_ATTESTATION_CONTRACT,
    D000_CROSS_TRACK_ENSEMBLE_REPORT_CONTRACT,
    D000_LOGIT_RSET_BLEND_REPORT_CONTRACT,
    D000_LOGIT_RSET_FLAT8_REPORT_CONTRACT,
)


def artifact(payload: Mapping[str, Any], *, contract: str) -> dict[str, Any]:
    if contract not in CONTRACTS:
        raise ValueError("unknown HCWDL-MHPE-TRI60 contract")
    body = dict(payload)
    body["contract"] = contract
    body["schema_version"] = SCHEMA_VERSION
    return with_content_hash(body)


def validate_artifact(value: Mapping[str, Any], *, contract: str) -> str:
    if contract not in CONTRACTS:
        raise ValueError("unknown HCWDL-MHPE-TRI60 contract")
    return validate_content_hash(
        value, expected_contract=contract, expected_schema_version=SCHEMA_VERSION,
    )


def hashes(values: Mapping[str, str]) -> dict[str, str]:
    if not values:
        raise ValueError("HCWDL-MHPE-TRI60 parent registry is empty")
    return {
        str(key): require_sha256(value, name=str(key))
        for key, value in sorted(values.items())
    }


def absolute_paths(values: Mapping[str, str | Path]) -> dict[str, str]:
    if not values:
        raise ValueError("HCWDL-MHPE-TRI60 path registry is empty")
    return {
        str(key): str(Path(value).resolve()) for key, value in sorted(values.items())
    }


__all__ = [name for name in globals() if name.endswith("_CONTRACT")] + [
    "CONTRACTS", "SCHEMA_VERSION", "absolute_paths", "artifact", "hashes",
    "validate_artifact",
]
