"""Versioned contracts for the persistent-HLT MT20 four-spine campaign."""

from __future__ import annotations

from typing import Final, Mapping, Any

from hlt_classification.data.cache_contracts import (
    validate_content_hash,
    with_content_hash,
)


PREFIX: Final = "HCWDL_TRI100_FOUR_SPINE_FULLCARD_PERSISTENT_HLT_MT20"
GRAPH_CONTRACT: Final = f"{PREFIX}_GRAPH/v1"
RECIPE_CONTRACT: Final = f"{PREFIX}_RECIPE/v1"
SOURCE_LOCK_CONTRACT: Final = f"{PREFIX}_SOURCE_LOCK/v1"
SUPPORT_AUDIT_CONTRACT: Final = f"{PREFIX}_SUPPORT_AUDIT/v1"
EXECUTION_ACCEPTANCE_CONTRACT: Final = f"{PREFIX}_EXECUTION_ACCEPTANCE/v1"
SPEC_CONTRACT: Final = f"{PREFIX}_CAMPAIGN_SPEC/v1"
PLAN_CONTRACT: Final = f"{PREFIX}_COMMAND_PLAN/v1"
TRAINING_REPORT_CONTRACT: Final = f"{PREFIX}_TRAINING_REPORT/v1"
SELECTED_CHECKPOINT_CONTRACT: Final = f"{PREFIX}_SELECTED_CHECKPOINT/v1"
FINAL_CHECKPOINT_CONTRACT: Final = f"{PREFIX}_FINAL_CHECKPOINT/v1"
PROBABILITY_SHARD_CONTRACT: Final = f"{PREFIX}_PROBABILITY_SHARD/v1"
PROBABILITY_MANIFEST_CONTRACT: Final = f"{PREFIX}_PROBABILITY_MANIFEST/v1"
PROBABILITY_LOCK_CONTRACT: Final = f"{PREFIX}_PROBABILITY_LOCK/v1"
MIXTURE_REGISTRY_CONTRACT: Final = f"{PREFIX}_RAM_MIXTURE_REGISTRY/v1"
STAGE_REPORT_CONTRACT: Final = f"{PREFIX}_STAGE_REPORT/v1"
AGGREGATE_CONTRACT: Final = f"{PREFIX}_AGGREGATE/v1"
COMPLETE_CONTRACT: Final = f"{PREFIX}_CAMPAIGN_COMPLETE/v1"
RECOVERY_SPEC_CONTRACT: Final = f"{PREFIX}_RECOVERY_SPEC/v1"
MONITOR_CONTRACT: Final = f"{PREFIX}_MONITOR/v1"
SCHEMA_VERSION: Final = 1

CONTRACTS: Final = (
    GRAPH_CONTRACT, RECIPE_CONTRACT, SOURCE_LOCK_CONTRACT,
    SUPPORT_AUDIT_CONTRACT, EXECUTION_ACCEPTANCE_CONTRACT, SPEC_CONTRACT,
    PLAN_CONTRACT, TRAINING_REPORT_CONTRACT, SELECTED_CHECKPOINT_CONTRACT,
    FINAL_CHECKPOINT_CONTRACT, PROBABILITY_SHARD_CONTRACT,
    PROBABILITY_MANIFEST_CONTRACT, PROBABILITY_LOCK_CONTRACT,
    MIXTURE_REGISTRY_CONTRACT, STAGE_REPORT_CONTRACT, AGGREGATE_CONTRACT,
    COMPLETE_CONTRACT, RECOVERY_SPEC_CONTRACT, MONITOR_CONTRACT,
)


def artifact(payload: Mapping[str, Any], *, contract: str) -> dict[str, Any]:
    if contract not in CONTRACTS:
        raise ValueError("MT20 artifact contract differs")
    return with_content_hash({
        "contract": contract,
        "schema_version": SCHEMA_VERSION,
        **dict(payload),
    })


def validate_artifact(value: Mapping[str, Any], *, contract: str) -> str:
    if contract not in CONTRACTS:
        raise ValueError("MT20 artifact contract differs")
    return validate_content_hash(
        value,
        expected_contract=contract,
        expected_schema_version=SCHEMA_VERSION,
    )


__all__ = [
    "AGGREGATE_CONTRACT", "COMPLETE_CONTRACT", "CONTRACTS",
    "EXECUTION_ACCEPTANCE_CONTRACT", "FINAL_CHECKPOINT_CONTRACT",
    "GRAPH_CONTRACT", "MIXTURE_REGISTRY_CONTRACT", "MONITOR_CONTRACT",
    "PLAN_CONTRACT", "PREFIX", "PROBABILITY_LOCK_CONTRACT",
    "PROBABILITY_MANIFEST_CONTRACT", "PROBABILITY_SHARD_CONTRACT",
    "RECIPE_CONTRACT", "RECOVERY_SPEC_CONTRACT", "SCHEMA_VERSION",
    "SELECTED_CHECKPOINT_CONTRACT", "SOURCE_LOCK_CONTRACT", "SPEC_CONTRACT",
    "STAGE_REPORT_CONTRACT", "SUPPORT_AUDIT_CONTRACT",
    "TRAINING_REPORT_CONTRACT", "artifact", "validate_artifact",
]
